# Generated by Django 5.1.15 on 2026-03-27 15:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("finance", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="expense",
            name="contribution_category",
            field=models.ForeignKey(
                blank=True,
                help_text="The contribution fund this expense is drawn from (optional).",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="expenses",
                to="finance.contributioncategory",
                verbose_name="Fund source",
            ),
        ),
    ]
